### PR TITLE
Implement Hypervisor field on instances

### PR DESCRIPTION
**Pull request by nesitor**
Problem: Instances with QEMU hypervisor cannot be created.

Solution: Implement hypervisor field into create_instance method.

### CODE REVIEW

**Comment by hoh** [comment]
Nice, can we add a unit test to prevent regressions ?

**Comment by hoh** [comment]
Tests are failing due to `isort`, can you fix that ?

**Comment by MHHukiewitz** [comment]
And now black is failing ^^'

**Comment by nesitor** [comment]
> And now black is failing ^^'

I already passed black on whole `src` folder, but in this project also we check the `tests` and the `examples` folder. Already fixed that issues.

**Comment by hoh** [comment]
Tests fail due to:
``` 
>       assert instance_message.content.hypervisor == HypervisorType.firecracker
E       AttributeError: 'InstanceContent' object has no attribute 'hypervisor'
```

**Review by MHHukiewitz — APPROVED** [review]
LGTM

**Pull request merged**
